### ISSUE TITLE
Build failure after removal of inaugural-openfyde repo

### ISSUE THREAD

**Issue by sepotvin** [openFyde/overlay-rock5b-openfyde#19]
Hi,

When trying to do the `setup_board` step with a clean fetched repo, the following error occur, probably due to the removal of the inaugural-openfyde repo in commit https://github.com/openFyde/manifest/commit/7612a71c9727e81918ebe0afde5281ded4a35172

```
(cr) (release-R108-15183.B/(4f43ce0...)) spotvin@Obelix ~/chromiumos/src/scripts $ setup_board --board=rock5b-openfyde
15:11:05.217: INFO: Updating chroot.
15:11:05.217: INFO: run: /mnt/host/source/src/scripts/update_chroot --toolchain_boards rock5b-openfyde '--backtrack=10' --usepkg
15:11:05.321 INFO    : Updating chroot
15:11:05.325 INFO    : Clearing shadow utils lockfiles under /
15:11:05.327 INFO    : Updating cross-compilers
15:11:05.328 INFO    : Running: sudo -E /mnt/host/source/chromite/bin/cros_setup_toolchains --include-boards=rock5b-openfyde
cros_setup_toolchains: Unhandled exception:
Traceback (most recent call last):
  File "/mnt/host/source/chromite/bin/cros_setup_toolchains", line 217, in <module>
    DoMain()
  File "/mnt/host/source/chromite/bin/cros_setup_toolchains", line 213, in DoMain
    commandline.ScriptWrapperMain(FindTarget)
  File "/mnt/host/source/chromite/lib/commandline.py", line 1235, in ScriptWrapperMain
    ret = target(argv[1:])
  File "/mnt/host/source/chromite/scripts/cros_setup_toolchains.py", line 1551, in main
    root=root,
  File "/mnt/host/source/chromite/scripts/cros_setup_toolchains.py", line 773, in UpdateToolchains
    targets.update(toolchain.GetToolchainsForBoard(board))
  File "/mnt/host/source/chromite/lib/toolchain.py", line 95, in GetToolchainsForBoard
    buildroot=buildroot,
  File "/mnt/host/source/chromite/lib/portage_util.py", line 259, in FindOverlays
    overlays = _ListOverlays(board=board, buildroot=buildroot)
  File "/mnt/host/source/chromite/lib/portage_util.py", line 236, in _ListOverlays
    found_pub = _AddRepo(board, optional=True)
  File "/mnt/host/source/chromite/lib/portage_util.py", line 220, in _AddRepo
    _AddRepo(master)
  File "/mnt/host/source/chromite/lib/portage_util.py", line 220, in _AddRepo
    _AddRepo(master)
  File "/mnt/host/source/chromite/lib/portage_util.py", line 215, in _AddRepo
    raise MissingOverlayError("%s was not found" % repo)
chromite.lib.portage_util.MissingOverlayError: inaugural-openfyde was not found
15:11:05.692: ERROR: Error occurred while updating the chroot. See the logs for more information.
```

**Comment by Damenly** [comment]
Sorry for the late reply. The missing overlays have been fixed just now. You can pull r108-dev 
 https://github.com/openFyde/manifest again then call `repo sync `then inaugural-openfyde  should appear.

**Comment by sepotvin** [comment]
Thanks for fixing the missing inaugural-openfyde overlay. After updating to the latest manifest and doing a `repo sync`, I get another missing repository, `archero` this time:
```
(cr) (release-R108-15183.B/(4f43ce0...)) spotvin@Obelix ~/chromiumos/src/scripts $ setup_board --board=rock5b-openfyde
16:36:52.637: INFO: Updating chroot.
16:36:52.637: INFO: run: /mnt/host/source/src/scripts/update_chroot --toolchain_boards rock5b-openfyde '--backtrack=10' --usepkg
16:36:52.745 INFO    : Updating chroot
16:36:52.749 INFO    : Clearing shadow utils lockfiles under /
16:36:52.751 INFO    : Updating cross-compilers
16:36:52.752 INFO    : Running: sudo -E /mnt/host/source/chromite/bin/cros_setup_toolchains --include-boards=rock5b-openfyde
cros_setup_toolchains: Unhandled exception:
Traceback (most recent call last):
  File "/mnt/host/source/chromite/bin/cros_setup_toolchains", line 217, in <module>
    DoMain()
  File "/mnt/host/source/chromite/bin/cros_setup_toolchains", line 213, in DoMain
    commandline.ScriptWrapperMain(FindTarget)
  File "/mnt/host/source/chromite/lib/commandline.py", line 1235, in ScriptWrapperMain
    ret = target(argv[1:])
  File "/mnt/host/source/chromite/scripts/cros_setup_toolchains.py", line 1551, in main
    root=root,
  File "/mnt/host/source/chromite/scripts/cros_setup_toolchains.py", line 773, in UpdateToolchains
    targets.update(toolchain.GetToolchainsForBoard(board))
  File "/mnt/host/source/chromite/lib/toolchain.py", line 95, in GetToolchainsForBoard
    buildroot=buildroot,
  File "/mnt/host/source/chromite/lib/portage_util.py", line 259, in FindOverlays
    overlays = _ListOverlays(board=board, buildroot=buildroot)
  File "/mnt/host/source/chromite/lib/portage_util.py", line 236, in _ListOverlays
    found_pub = _AddRepo(board, optional=True)
  File "/mnt/host/source/chromite/lib/portage_util.py", line 220, in _AddRepo
    _AddRepo(master)
  File "/mnt/host/source/chromite/lib/portage_util.py", line 215, in _AddRepo
    raise MissingOverlayError("%s was not found" % repo)
chromite.lib.portage_util.MissingOverlayError: archero was not found
16:36:53.112: ERROR: Error occurred while updating the chroot. See the logs for more information.
```

**Comment by Damenly** [comment]
I see. Since ArcHero is still in develop status and unstable so the repo is only visible for our internal build.
You can find the overlay-rock5b-openfyde and apply the following:

```
diff --git a/metadata/layout.conf b/metadata/layout.conf
index 8170e7fbd248..49078249b06d 100644
--- a/metadata/layout.conf
+++ b/metadata/layout.conf
@@ -1,4 +1,4 @@
-masters = portage-stable chromiumos eclass-overlay rock5b-openfyde-base fyde-eclass archero
+masters = portage-stable chromiumos eclass-overlay rock5b-openfyde-base fyde-eclass
 profile-formats = portage-2 profile-default-eapi
 profile_eapi_when_unspecified = 5-progress
 repo-name = rock5b-openfyde
(END)
```
